### ISSUE TITLE
[Android] Build error

### ISSUE THREAD

**Issue by aryella-lacerda** [oblador/react-native-performance#19]
Hello! I followed the instructions for Android in the README, but got this error when I ran `npx react-native run-android`.

```
/Path/to/ReactNativeFlipper.java:24: error: package com.oblador.flipperperformanceplugin does not exist
import com.oblador.flipperperformanceplugin.FlipperReactPerformancePlugin;
                                           ^
Path/to/ReactNativeFlipper.java:35: error: cannot find symbol
      client.addPlugin(new FlipperReactPerformancePlugin(reactInstanceManager));
                           ^
  symbol:   class FlipperReactPerformancePlugin
  location: class ReactNativeFlipper
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

```

Have I done something wrong? Any help fixing it.

Other details:
- Words perfectly on iOS.
- package.json:
```
    "react-native": "0.63.4",
    "flipper-plugin-react-native-performance": "^0.5.0",
```

**Comment by oblador** [comment]
Hey! Version 0.5.0 only supports iOS, make sure you are on 0.6.0!

**Comment by aryella-lacerda** [comment]
Thanks, the build error went away! But the plugin's still not showing up for Android, not even in the "Unavailable Plugins" section:

![Screen Shot 2021-01-22 at 5 19 46 PM](https://user-images.githubusercontent.com/28730324/105541223-3660c380-5cd6-11eb-8656-dfc9934596bd.png)

It does show up in the iOS panel:

![Screen Shot 2021-01-22 at 5 16 27 PM](https://user-images.githubusercontent.com/28730324/105541341-5ee8bd80-5cd6-11eb-8665-ab085ae54f79.png)

Any idea what may be happening? 🤔

**Comment by oblador** [comment]
Hmm, not sure! Maybe you can compare your setup to the [example project](https://github.com/oblador/flipper-plugin-react-native-performance/tree/master/examples/vanilla)?

**Comment by oblador** [comment]
Did you manage this yet? You might want to check out the v1.0 that works a bit differently: https://github.com/oblador/react-native-performance/blob/master/packages/react-native-performance-flipper-reporter/README.md

**Comment by oblador** [comment]
Closing due to lack of replies.
