### ISSUE TITLE
How to see React Native Performance Flipper Reporter?

### ISSUE THREAD

**Issue by blackbing** [oblador/react-native-performance#45]
Hi I followed <https://github.com/oblador/react-native-performance/blob/master/packages/react-native-performance-flipper-reporter/README.md> to add the snippet。

how do I see the report?

**Comment by oblador** [comment]
Hi! You need the Flipper plugin for that, see this readme: https://github.com/oblador/react-native-performance/tree/master/packages/flipper-plugin-performance

**Comment by blackbing** [comment]
oh I see. thank you very much
