### ISSUE TITLE
Some markers are broken in Android

### ISSUE THREAD

**Issue by victorhqc** [oblador/react-native-performance#53]
## Description

Using some markers such as `runJsBundleEnd` are not currently working on Android. It may be related to these other issues, but I think it should be highlighted that those issues are affecting this package:

- https://github.com/facebook/react-native/issues/30315
- https://github.com/facebook/react-native/issues/23771

## Build details

- **Platform:** Android
- **Dependencies:**
  - **react-native:** `0.64.2`
  - **react-native-performance:** `2.0.0`

**Comment by oblador** [comment]
Cannot reproduce with latest RN/RNP
