### ISSUE TITLE
Meet an error when build iOS: No visible @interface for 'RCTEventEmitter' declares the selector 'invalidate'

### ISSUE THREAD

**Issue by Sioxas** [oblador/react-native-performance#75]
## Description

No visible @interface for 'RCTEventEmitter' declares the selector 'invalidate'

<img width="941" alt="image" src="https://user-images.githubusercontent.com/9740581/163749722-b27cd59f-43d0-42ce-9692-b024276d0bad.png">

## Build Details
**Xcode**: `13.3.1`
**react-native**: `0.62.2`
**react-native-performance**: `3.0.0`

**Comment by oblador** [comment]
3.0.0 requires React Native 0.68. Your version is ancient!
