### ISSUE TITLE
No data displayed

### ISSUE THREAD

**Issue by ZeroPie** [oblador/react-native-performance#76]
Hi,
i cannot get the plugin to show any data
Steps:
```
yarn add react-native-performance react-native-flipper react-native-performance-flipper-reporte
```
```
 require('react-native-performance-flipper-reporter').setupDefaultFlipperReporter();
```
Flipper stats are empty:
![Screenshot 2022-04-18 at 20 25 46](https://user-images.githubusercontent.com/8741666/163901815-d4b61bc1-1542-4f76-b8f9-1c449ec3e609.png)

**Comment by obiwankenoobi** [comment]
same here

**Comment by oblador** [comment]
Is the native module linked and app recompiled?

**Comment by obiwankenoobi** [comment]
Work. can be closed
