### ISSUE TITLE
Feature Request: Disable via ENV

### ISSUE THREAD

**Issue by jakobo** [oblador/react-native-performance#87]
When users are building on the expo framework, the EAS remote build system runs with the `CI=1` ENV value set, which automatically disabled Flipper. ([ref](https://docs.expo.dev/build-reference/variables/#built-in-environment-variables)). This makes it possible to make a build that autolinks react-native-performance, but with Flipper missing.

**Proposal**
If we could add an `ENV` check to the [autolink podspec](https://github.com/oblador/react-native-performance/blob/master/packages/react-native-performance/react-native-performance.podspec), rnp could be explicitly disabled for a build. Unfortunately, the default of `ENV['CI']` doesn't work in expo because of the linked docs above.

```
if !ENV['RNP_DISABLE'] == '1' then
  Pod::Spec.new do |s|
  # ...
end
```

**Related**
* https://github.com/jakobo/expo-community-flipper/issues/13
* [Expo build reference - ENV](https://docs.expo.dev/build-reference/variables/#built-in-environment-variables)

**Comment by oblador** [comment]
You can control this via `react-native.config.js` which is what I’d recommend instead

**Comment by jakobo** [comment]
Thanks. I'll let the OP know they can use `react-native.config.js` to disable auto-linking this library when they're making a non-flipper build.
